name: MagnerScuba
favicon: null
layout_spectrum: 0.68263
typography_spectrum: 0.44007
title: Mark M. Magner - Scuba Photos
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c0d5f4'
    - '#c4bca9'
    - '#87959e'
    - '#100b08'
    - '#4c4134'
  brandStrength: 0.5
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
