name: MagnerScuba
favicon: null
layout_spectrum: 0.8821441021282226
typography_spectrum: 0.6316909263841808
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.9958057159092277
  lightness: 0.4995601559057832
  saturation: 0.6917668036185205
  rhythmicContrast: 0.6186453821137547
purpose: []
